language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

script:
  - yarn lint
  - yarn build --prod --base-href /ag-form/
  - mv dist/auxiliumgroup/index.html dist/auxiliumgroup/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/auxiliumgroup
  on:
    branch: master
